# Spring Server Config
server.port=8080
server.servlet.context-path=/

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/civic_portal
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# File Upload Limit Configuration (For Base64 and Multi-part)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Custom Security Settings
jwt.secret=sih25031-civic-secret-key-9988-sih25031-civic-secret-key-9988-sih25031-civic-secret-key-9988
# 7 days in milliseconds (7 * 24 * 60 * 60 * 1000)
jwt.expiration=604800000

# OpenAPI Swagger Documentation Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
